package:
  name: fedscgen
  version: "0.1.0"

source:
  path: ..

build:
  noarch: false
  script: python -m pip install .

requirements:
  build:
    - python >=3.9
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.9
    - anndata ==0.9.1
    - scgen ==2.1.0
    - scanpy ==1.9.3
    - scarches ==0.5.9
    - scib ==1.1.3
    - scvi-tools ==1.0.2
    - torch ==2.0.1
    - pytorch-lightning ==2.0.5
    - crypten ==0.4.1
    - matplotlib
    - seaborn
    - pandas
    - numpy
    - r-base ==4.2
    - rpy2 ==3.5.13
    - r-devtools
    - r-readr
    - r-ggplot2
    - r-remotes
    - r-stringr
    - r-data.table

test:
  imports:
    - fedscgen
    - scanpy
    - torch
    - rpy2

about:
  home: https://github.com/YOUR_USERNAME/fedscgen
  license: MIT
  license_file: LICENSE
  summary: "Privacy-aware federated batch effect correction for single-cell RNA-seq"
  description: |
    FedscGen is a federated framework for harmonizing scRNA-seq data using privacy-preserving methods such as SMPC. It supports centralized and federated scenarios with tools like ScGen and scVI, implemented in PyTorch and CrypTen.
  dev_url: https://github.com/YOUR_USERNAME/fedscgen
